# --- IQL specific parameters ---

mac: "jumpstart_mac"
# use epsilon greedy action selector
action_selector: "filtered_const_epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 300000
evaluation_epsilon: 0.0
runner: "episode"

# jumpstart_policy configs
jumpstart_action_selector: "haa_selector"
jumpstart_epsilon_start: 1
jumpstart_epsilon_finish: 0
jumpstart_epsilon_anneal_time: 150000
jumpstart_evaluation_epsilon: 0

buffer_size: 1000

use_mps: True

t_max: 500000

# update the target network every {} episodes
target_update_interval_or_tau: 0.01

agent: "flat_const_agent" # Default constellation agent (multi-component benefit observation)
num_filters: 5 # Number of filters
hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False
use_rnn: False

# use the Q_Learner to train

agent_output_type: "q"
learner: "filtered_q_learner"
standardise_returns: False
standardise_rewards: True
double_q: True
mixer: # Mixer becomes None

name: "filtered_iql"
