# --- IQL SAP specific parameters ---

mac: "jumpstart_mac"
# use epsilon greedy action selector
action_selector: "filtered_const_sap"
epsilon_start: 0.15
epsilon_finish: 0.005
epsilon_anneal_time: 300000
evaluation_epsilon: 0
# jumpstart_policy configs
jumpstart_action_selector: "nha_selector"
jumpstart_epsilon_start: 1
jumpstart_epsilon_finish: 0
jumpstart_epsilon_anneal_time: 150000
jumpstart_evaluation_epsilon: 0

# Pretraining configs
use_offline_dataset: False #use JumpstartRL rather than offline dataset by default.
offline_dataset_path: null
pretrain_fn: null
pretrain_batches: 1000

t_max: 800000

runner: "episode"

buffer_size: 2000

# update the target network every {} episodes
target_update_interval_or_tau: 0.01

# --- Agent parameters ---
agent: "custom_cnn_const_agent" # Default constellation agent (multi-component benefit observation)
num_filters: 5 # Number of filters
hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False
use_rnn: False

# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True
agent_output_type: "q"
learner: "filtered_sap_q_learner"
double_q: True
use_rnn: False
mixer:


name: "iql_sap"
