env: "benefit_obs_env"

env_args:
  key: null
  episode_step_limit: 50
  bids_as_actions: null

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
use_wandb: False
wandb_run_name: null