env: "mock_constellation_env"

env_args:
  n: 10
  num_tasks: 10
  T: 15
  L: 3
  lambda_: 0.5
  bids_as_actions: null

cooperative_rewards: False

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
use_wandb: False
wandb_run_name: null