env: "mock_constellation_env"

env_args:
  n: 20
  m: 25
  T: 20
  L: 3
  lambda_: 0.5
  bids_as_actions: null

test_greedy: True
test_nepisode: 50
test_interval: 2500
log_interval: 5000
runner_log_interval: 2500
learner_log_interval: 2500
use_wandb: False
wandb_run_name: null

obs_agent_id: False #dont need to observe agent id bc observing benefits