env: "real_power_constellation_env"

env_args:
  num_planes: 18
  num_sats_per_plane: 18
  m: 450
  T: 100
  L: 3
  lambda_: 0.5
  bids_as_actions: null
  N: 10
  M: 10

# Scheme related arguments
cooperative_rewards: False

test_greedy: True
test_nepisode: 20
test_interval: 50000
log_interval: 50000
runner_log_interval: 5000
learner_log_interval: 5000
t_max: 1000000
use_wandb: False
wandb_run_name: null